# Continuos Delivery/Deployment to Docker Hub

on:
  push:
    tags:
        - "v*.*.*"
        
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
      
      - run: echo "CONTAINER_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV 

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build tmux
        id: build_tmux
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: |
            VERSION=${{ env.CONTAINER_VERSION }} 
          push: true
          tags: |
            seebaktec/tmux:latest
            seebaktec/tmux:${{ env.CONTAINER_VERSION }} 

      - name: Image digest
        run: echo ${{ steps.build_tmux.outputs.digest }}
